version: '3.9'

services:
  django:
    build:
      context: .
      dockerfile: devops/Dockerfile
    image: pizzeria:0.0.1
    ports:
      - "8080:8080"
    env_file:
      - pizzeria/.env
    volumes:
      - .:/app
    command: ["python", "pizzeria/manage.py", "runserver", "0.0.0.0:8080"]
