# Generated by Django 4.2.17 on 2025-01-09 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_order_orderitem"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"verbose_name": "Order", "verbose_name_plural": "Orders"},
        ),
    ]
