# Generated by Django 4.2.17 on 2025-01-12 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_recipe_price"),
        ("nutrition", "0005_custompizza"),
        ("cart", "0003_alter_order_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="custom_pizza",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="nutrition.custompizza",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="custom_pizza",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="nutrition.custompizza",
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="recipe",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="recipes.recipe",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="recipe",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="recipes.recipe",
            ),
        ),
    ]
