# Generated by Django 4.2.17 on 2025-01-07 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="price",
            field=models.FloatField(default=0.0),
        ),
    ]
