# Generated by Django 4.2.17 on 2025-01-12 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_recipe_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.URLField(max_length=500),
        ),
    ]
