# Generated by Django 4.2.17 on 2025-01-12 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_alter_recipe_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.URLField(max_length=2000),
        ),
    ]
