# Generated by Django 4.2.17 on 2025-01-09 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_userprofile_address_userprofile_city_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
    ]
