# Generated by Django 4.2.17 on 2025-01-11 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("calories", models.FloatField(default=0)),
                ("fats", models.FloatField(default=0)),
                ("proteins", models.FloatField(default=0)),
                ("carbohydrates", models.FloatField(default=0)),
                ("price_per_unit", models.FloatField(default=0)),
                ("unit", models.CharField(default="grams", max_length=50)),
            ],
        ),
    ]
