# Generated by Django 4.2.17 on 2025-01-11 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ingredient",
            old_name="calories",
            new_name="calories_per_unit",
        ),
        migrations.RenameField(
            model_name="ingredient",
            old_name="carbohydrates",
            new_name="carbohydrates_per_unit",
        ),
        migrations.RenameField(
            model_name="ingredient",
            old_name="fats",
            new_name="fats_per_unit",
        ),
        migrations.RenameField(
            model_name="ingredient",
            old_name="proteins",
            new_name="proteins_per_unit",
        ),
    ]
