# Generated by Django 4.2.17 on 2025-01-11 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0002_rename_calories_ingredient_calories_per_unit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="category",
            field=models.CharField(
                choices=[("Base", "Base"), ("Topping", "Topping")],
                default="Topping",
                max_length=10,
            ),
        ),
    ]
