# Generated by Django 4.2.17 on 2025-01-11 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0003_ingredient_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="category",
            field=models.CharField(
                choices=[("Base", "Base"), ("Sauce", "Sauce"), ("Topping", "Topping")],
                default="Topping",
                max_length=10,
            ),
        ),
    ]
