# Generated by Django 4.2.17 on 2025-01-12 02:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("nutrition", "0004_alter_ingredient_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomPizza",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Custom Pizza", max_length=255)),
                ("base", models.CharField(max_length=100)),
                ("sauce", models.CharField(max_length=100)),
                ("toppings", models.TextField()),
                ("calories", models.FloatField(default=0)),
                ("price", models.FloatField(default=12.0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_pizzas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
